### ISSUE TITLE
CI failing on pytest since Jun 30th

### ISSUE THREAD

**Issue by mikaelarguedas** [Karsten1987/roscon2018#67]
From https://travis-ci.org/Karsten1987/confbot_robot/jobs/558110322:

```
[4.875s] ERROR:colcon.colcon_core.task.python.test:Exception in Python testing step extension 'pytest': cannot import name 'EXIT_TESTSFAILED'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/colcon_core/task/python/test/__init__.py", line 75, in test
    return await extension.step(self.context, env, setup_py_data)
  File "/usr/local/lib/python3.6/dist-packages/colcon_core/task/python/test/pytest.py", line 157, in step
    from _pytest.main import EXIT_TESTSFAILED
ImportError: cannot import name 'EXIT_TESTSFAILED'
```

**Comment by mikaelarguedas** [comment]
The error comes from changes in pytest 5.0.0 and later that are not supported in `colcon_core`.
Attempted fix at https://github.com/colcon/colcon-core/pull/198

**Comment by mikaelarguedas** [comment]
new version of colcon (colcon-core 0.3.23) with the fix has been released. CI now passes: https://travis-ci.org/Karsten1987/confbot_robot/builds/560222783?utm_source=github_status&utm_medium=notification
